config/routes.rb
Rails.application.routes.draw do

  devise_for :admins#, :skip => [:registrations] 
  devise_scope :admin do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_out', to: 'logout'
  end

  get '/report', to: 'teachers#report', as: 'report'
  post 'email_me' => 'teachers#email_me'
  get 'sent_mail' => 'teachers#index'
  resources :role_credentials
  resources :teachers
  resources :roles do
    resources :tracks
  end
  resources :credentials
  
  root 'teachers#explore'

end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :teacher
  has_many :role_credentials, dependent: :destroy
  has_many :credentials, :through => :role_credentials, dependent: :destroy
  has_many :tracks, dependent: :destroy

  validates :name, uniqueness: true, :length => {minimum: 1}
  
  def self.find_unique_names
    return(Role.all.uniq {|r| r.name})  
  end


	def exams
		credentials.where(exam: true)
	end

	def certificates
		credentials.all - exams
	end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :authenticate_admin!
  before_action :set_role, only: [:show, :edit, :update, :destroy]

  # GET /roles
  # GET /roles.json
  def index
    @roles = Role.where('hidden IS NULL OR hidden IS FALSE').order('name ASC').all
    @hidden = Role.where('hidden IS TRUE').order('name ASC').all
  end

  # GET /roles/1
  # GET /roles/1.json
  def show
    @credentials = Credential.order('name ASC').all.uniq{|c| c.name}
    @role_credential = @role.role_credentials.new

    @exams = @role.credentials.where(:exam => true).order('name ASC')
    @creds = @role.credentials.all - @exams
  end

  # GET /roles/new
  def new
    @role = Role.new
  end

  # GET /roles/1/edit
  def edit
  end

  # POST /roles
  # POST /roles.json
  def create
    @role = Role.new(role_params)

    respond_to do |format|
      if @role.save
        format.html { redirect_to @role, notice: 'Role was successfully created.' }
        format.json { render :show, status: :created, location: @role }
      else
        format.html { render :new }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /roles/1
  # PATCH/PUT /roles/1.json
  def update
    respond_to do |format|
      if @role.update(role_params)
        format.html { redirect_to @role, notice: 'Role was successfully updated.' }
        format.json { render :show, status: :ok, location: @role }
      else
        format.html { render :edit }
        format.json { render json: @role.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /roles/1
  # DELETE /roles/1.json
  def destroy
    @role.hidden = true
    @role.save
    respond_to do |format|
      format.html { redirect_to roles_url, notice: 'Role was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_role
      @role = Role.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def role_params
      params.require(:role).permit(:name, :hidden, :special_education)
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= form_for(@role) do |f| %>
  <% if @role.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@role.errors.count, "error") %> prohibited this role from being saved:</h2>

      <ul>
      <% @role.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
<br />
    <%= f.label :special_education %> 
    <%= f.check_box :special_education %>
<br /><br />
    <%= f.label :hidden %> 
    <%= f.check_box :hidden %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/roles/edit.html.erb
<h1>Editing Role</h1>

<%= render 'form' %>

<%= link_to 'Show', @role %> |
<%= link_to 'Back', roles_path %>

app/views/roles/explore.html.erb
<-- <%= form_for @teacher, :url => {controller: Role, action: create} do |f| %>
 <%= f.select :role, @unique_roles, include_blank: true %>

<% end %> 

<%= @yes %>
<%= @unique_roles.length %>


    
    -->

</-->

roles#explore

app/views/roles/index.html.erb
<h1>Listing Roles</h1>

<h2>Active Roles</h2>
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Complete?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><% if role.credentials.count == 0%><span style="background-color:red">!!!</span><% end %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
        <td><%= link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Hidden Roles</h2>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @hidden.each do |role| %>
      <tr>
        <td><%= role.name %></td>
        <td><%= link_to 'Show', role %></td>
        <td><%= link_to 'Edit', edit_role_path(role) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Role', new_role_path %>

app/views/roles/new.html.erb
<h1>New Role</h1>

<%= render 'form' %>

<%= link_to 'Back', roles_path %>

app/views/roles/show.html.erb
<h3><%= @role.name %></h3>
<p>Special Education: <%= @role.special_education %></p>

<b><%= pluralize @role.credentials.length, "credential" %> required for this position:</b>
<h4>Exams</h4>
<%= render partial: "table", locals: {credentials: @exams} %>
<h4>Certificates</h4>
<%= render partial: "table", locals: {credentials: @creds} %>

<p>Create a <%= link_to "new credential", new_credential_path %>.</p>
<hr />
<b>Attach a Credential</b>

<%= render :partial => "role_credentials/form", locals: {role: @role} %>


<%= link_to 'Edit', edit_role_path(@role) %> |
<%= link_to 'Back', roles_path %>