config/routes.rb
Rails.application.routes.draw do

  devise_for :admins#, :skip => [:registrations] 
  devise_scope :admin do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_out', to: 'logout'
  end

  get '/report', to: 'teachers#report', as: 'report'
  post 'email_me' => 'teachers#email_me'
  get 'sent_mail' => 'teachers#index'
  resources :role_credentials
  resources :teachers
  resources :roles do
    resources :tracks
  end
  resources :credentials
  
  root 'teachers#explore'

end

app/models/credential.rb
class Credential < ActiveRecord::Base
#  include Bootsy::Container

  has_many :role_credentials
  has_many :roles, :through => :role_credentials

  has_many :teacher_credentials, dependent: :destroy 

  accepts_nested_attributes_for :roles

  validates :name, presence: true, length: { minimum: 3 }, uniqueness: true
  

end

app/controllers/credentials_controller.rb
class CredentialsController < ApplicationController
  before_filter :authenticate_admin!
  before_action :set_credential, :except => [:create, :new, :index, :email_me]
  
  def index
    @exams = Credential.where(:exam => true).order('name ASC')
    @creds = Credential.all - @exams
  end

  def new
    @credential = Credential.new
  end

  def show

  end

  def create
    @credential = Credential.new(credential_params)

    respond_to do |format|
      if @credential.save
        format.html { redirect_to @credential, notice: 'Credential was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  
  def edit
  end
  
  def update
    respond_to do |format|
      if @credential.update(credential_params)
        format.html { redirect_to @credential, notice: 'Credential was successfully updated.' }
        format.json { render :show, status: :ok, location: @credential }
        else
        format.html { render :edit }
      end
    end
  end
  
  def destroy
    @credential.destroy
    redirect_to credentials_path   
  end

 
  private

    def set_credential
      @credential = Credential.find(params[:id])
    end
  
    def credential_params
      params.require(:credential).permit(:name, :note, :link, :exam, :credential_ids => [])
    end
end

app/helpers/credentials_helper.rb
module CredentialsHelper
end

app/views/credentials/_credential.html.erb
<td><%= credential.name %></td>
<td><%= link_to credential.link, credential.link %></td>
<td><span class ="ss"><%= simple_format credential.note %></span></td>

app/views/credentials/_credential_table.html.erb
<% edit = false if local_assigns[:edit].nil? %>
<table class="table table-bordered">
	<thead>
	  <tr>
	    <td><%= table_header %></td>
	    <td>Web Link</td>
	    <td>Notes</td>
	    <% if edit %>
	    <td></td>
	    <td></td>
	    <% end %>
    </tr>
  </thead>
  <tbody>
	<% credentials.each do |c| %>
		<tr> 
		  	<%= render partial: "credentials/credential", locals: {credential: c} %>
	    <% if edit %>
	    <td><%= link_to 'edit', edit_credential_path(c) %></td>
	    <td><%= link_to 'Destroy', c, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	    <% end %>
	  	</tr>
	<% end %>
  </tbody>
</table>

app/views/credentials/_form.html.erb
<%= form_for([@role, @credential]) do |f| %>
<% if @credential.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@credential.errors.count, "error") %> prohibited this role from being saved:</h2>
<ul>
<% @credential.errors.full_messages.each do |message| %>
<li><%= message %></li>
<% end %>
</ul>
</div>
<% end %>
<p>
<%= f.label :name %><br>
<%= f.text_field :name %>
</p>
<p>
<%= f.label :link %><br />
<%= f.text_field :link %>
</p>
<p>
<%= f.label :note %><br />
<%= f.text_area :note, cols: 100, rows: 24 %>
</p>
<p>
<%= f.label :exam %><br />
<%= f.check_box :exam %>
</p>
<p>
<%= f.submit %>
</p>
<% end %>

app/views/credentials/_reminder_text.html.erb
<p>Many teachers have found it useful to have information about their certifcation emailed to them.  If you would like to have relevant certifcation emailed to you, please:</p>
<ul>
	<li>Enter your name and email in the corresponding boxes below.</li>
	<li>Click the button to recieve this important information.</li>
</ul>

app/views/credentials/_tims.html.erb
<h2>Steps</h2>
<ol>
	<li>Create a profile on the Pennsylvania's Department of Education (PDE) Teacher Management Information System (TIMS). You can find detailed instructions for registration with TIMS <%= link_to "here", "http://www.education.pa.gov/Documents/Teachers-Administrators/Certifications/TIMS/Getting%20Started%20with%20TIMS.pdf", :target => "_blank" %>. <b>Write down a copy of your PPID for reference</b>.</li>
	<li>Take, pass, and submit copies of required Praxis/PECT scores to the PDE.</li>
	<li>Submit credential applications  from the list below. </li>
</ol>

app/views/credentials/edit.html.erb
<%= render 'form' %>

app/views/credentials/index.html.erb
<%= link_to "New Credential", new_credential_path %>
<br />
<br />

<% exams = []
   creds = [] %>
<h2>Exams</h2>
<%= render partial: "credentials/credential_table", locals: {credentials: @exams, table_header: "Exams", edit: true} %>

<h2>Credentials</h2>
<%= render partial: "credentials/credential_table", locals: {credentials: @creds, table_header: "Credentials", edit: true} %>

app/views/credentials/new.html.erb
<%= render 'form' %>

app/views/credentials/show.html.erb
<h3>Credential</h3>
Name: <%= @credential.name %><br />
Link: <%= @credential.link %><br />
<span class="ss">
	Note: <%= simple_format @credential.note %>
</span><br />
Exam: <%= @credential.exam %><br />
<%= link_to 'Edit', edit_credential_path(@credential) %> |
<%= link_to 'Back', credentials_path %>
<br />
<br />
<%= link_to 'new credential', new_credential_path %>