config/routes.rb
Rails.application.routes.draw do

  devise_for :admins#, :skip => [:registrations] 
  devise_scope :admin do
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_out', to: 'logout'
  end

  get '/report', to: 'teachers#report', as: 'report'
  post 'email_me' => 'teachers#email_me'
  get 'sent_mail' => 'teachers#index'
  resources :role_credentials
  resources :teachers
  resources :roles do
    resources :tracks
  end
  resources :credentials
  
  root 'teachers#explore'

end

app/views/layouts/_login.html.erb
<% if admin_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_admin_session_path, :method => :delete) %>        
  </li>
<% else %>
  <!-- <%= link_to('Admin Login', new_admin_session_path)  %> -->
<% end %>
<br />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KIPP Schools</title>
  <%= stylesheet_link_tag   'scaffolds' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<fdiv id = "container">
	<fdiv id = "header">
		<p class="centered"><%= link_to image_tag("KIPP_logo", id: "main_title"), "/" %></p>
		<%= link_to "Certificate Search", "/"%>
		<% if admin_signed_in? %>
		| <%= link_to "roles", roles_path %> | <%= link_to "credentials", credentials_path %> |<%= link_to "sent mail", "/sent_mail" %><% end %> 
		|
		<%= link_to "learn more about KIPP", "https://form.jotform.com/60984660991166" %><br />
		<%= render :partial => "layouts/login" %>
	</div>

	<fdiv id = "content">
		<p id = "notice" class = "notice"><%= notice || flash[:notice] %></p>
		<p id = "alert" class = "alert"><%= alert || flash[:alert] %></p>
		<% flash.clear %>
		<%= yield %>
	</div>
</div>
</body>
</html>